---
  TroveConfigurations.create_attach_and_detach_configuration:
    -
      args:
        values:
          wait_timeout: 30
        datastore: "mysql"
        datastore_version: "5.5"
      runner:
        type: "constant"
        times: 1
        concurrency: 1
      context:
        instance:
          flavor: "6"
          datastore: "mysql"
          datastore_version: "5.5"
          nics:
            [net-id: "78783337-5e7d-4a65-b58e-3e5dae89de17"]
          volume: 
            size: 1
