---
  TroveConfigurations.create_and_delete_configuration:
    -
      args:
        values:
          wait_timeout: 30
        datastore: "mysql"
        datastore_version: "5.5"
      runner:
        type: "constant"
        times: 1
        concurrency: 1
